Repository alexander-zuev/kollektiv, pull requests merged in 2024-10, with the labels that each got.

#74 Update bundle
  .gitattributes
  .pre-commit-config.yaml
  LICENSE.md
  README.md
  app.py
  docs/feature-scoping/0-2-0/evals-tbd.md
  docs/feature-scoping/0-2-0/evals-wip.md
  docs/feature-scoping/0-2-0/telemetry-tbd.md
  docs/feature-scoping/0-2-0/vector-storage-imp.md
  docs/user-guide.md
  poetry.lock
  pyproject.toml
  src/crawling/crawler.py
  src/data/example/example.md
  src/evaluation/__init__.py
  src/evaluation/eval_dataset.json
  src/evaluation/evaluation.py
  src/generation/claude_assistant.py
  src/utils/config.py
  src/vector_storage/document_summaries.json
  src/vector_storage/vector_db.py
Labels: bug, documentation, enhancement, refactor

#76 Setup rag eval az 24
  app.py
  docs/feature-scoping/0-2-0/evals-wip.md
  poetry.lock
  pyproject.toml
  src/core/component_initializer.py
  src/crawling/crawler.py
  src/data/example/example.md
  src/evaluation/eval_dataset.json
  src/evaluation/evaluation.py
  src/generation/claude_assistant.py
  src/generation/summary_manager.py
  src/utils/config.py
  src/vector_storage/document_summaries.json
  src/vector_storage/vector_db.py
  tests/test_claude_assistant.py
Labels: documentation, enhancement, refactor

#78 refactor(eval): finished refactoring to ragas 0.2.1
  poetry.lock
  scripts/generate_structure.py
  src/evaluation/evaluation.py
Labels: refactor

#82 refactor project structure script
  scripts/generate_structure.py
Labels: refactor

#84 Feature/rename to kollektiv
  .chainlit/config.toml
  .chainlit/translations/bn.json
  .chainlit/translations/en-US.json
  .chainlit/translations/gu.json
  .chainlit/translations/he-IL.json
  .chainlit/translations/hi.json
  .chainlit/translations/kn.json
  .chainlit/translations/ml.json
  .chainlit/translations/mr.json
  .chainlit/translations/ta.json
  .chainlit/translations/te.json
  .chainlit/translations/zh-CN.json
  .env.example
  .flake8
  .pre-commit-config.yaml
  CHANGELOG.md
  README.md
  app.py
  chainlit.md
  chainlit_app.py
  chainlit_poc.py
  docs/feature-scoping/0-2-0/chainlit-tbd.md
  docs/feature-scoping/0-2-0/commands-tbd.md
  docs/feature-scoping/0-2-0/evals[blocked].md
  docs/feature-scoping/0-2-0/rename.md
  docs/user-guide.md
  poetry.lock
  pyproject.toml
  scripts/generate_structure.py
  src/core/component_initializer.py
  src/crawling/crawler.py
  src/evaluation/evaluation.py
  src/generation/claude_assistant.py
  src/generation/summary_manager.py
  src/generation/tool_definitions.py
  src/processing/chunking.py
  src/ui/terminal_ui.py
  src/utils/logger.py
Labels: refactor

#85 docs: updated docstrings for all modules, functions in the application
  README.md
  app.py
  chainlit_app.py
  chainlit_poc.py
  src/generation/claude_assistant.py
  src/generation/summary_manager.py
  src/generation/tool_definitions.py
  src/processing/chunking.py
  src/utils/decorators.py
  src/utils/logger.py
  src/utils/output_formatter.py
  src/vector_storage/vector_db.py
  tests/test_app.py
  tests/test_chunking.py
  tests/test_claude_assistant.py
  tests/test_crawler.py
  tests/test_vector_db.py
Labels: documentation

#86 Refactor of crawler: proper job handling, webhooks, error handling
  .chainlit/config.toml
  .chainlit/translations/bn.json
  .chainlit/translations/en-US.json
  .chainlit/translations/gu.json
  .chainlit/translations/he-IL.json
  .chainlit/translations/hi.json
  .chainlit/translations/kn.json
  .chainlit/translations/ml.json
  .chainlit/translations/mr.json
  .chainlit/translations/ta.json
  .chainlit/translations/te.json
  .chainlit/translations/zh-CN.json
  .env.example
  .flake8
  .gitignore
  .pre-commit-config.yaml
  CHANGELOG.md
  LICENSE.md
  README.md
  app.py
  docs/feature-scoping/0-2-0/evals[blocked].md
  docs/feature-scoping/0-2-0/rename.md
  docs/feature-scoping/0-2-0/telemetry-tbd.md
  docs/feature-scoping/0-2-0/vector-storage-imp.md
  docs/user-guide.md
  poetry.lock
  pyproject.toml
  src/core/component_initializer.py
  src/crawling/crawler.py
  src/crawling/exceptions.py
  src/crawling/file_manager.py
  src/crawling/job_manager.py
  src/crawling/models.py
  src/crawling/webhook_handler.py
  src/data/example/example.md
  src/generation/claude_assistant.py
  src/generation/summary_manager.py
  src/interface/__init__.py
  src/interface/command_handler.py
  src/interface/flow_manager.py
  src/interface/message_handler.py
  src/interface/webhook_router.py
  src/kollektiv/__init__.py
  src/kollektiv/manager.py
  src/processing/chunking.py
  src/ui/terminal_ui.py
  src/utils/config.py
  src/vector_storage/document_summaries.json
  src/vector_storage/vector_db.py
  tests/__init__.py
  tests/test_chunking.py
  tests/test_claude_assistant.py
  tests/test_crawler.py
Labels: documentation, enhancement, refactor

#87 bugfix: incorrect import in manager
  src/kollektiv/manager.py
Labels: bug
